apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-sleep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine-sleep
  template:
    metadata:
      labels:
        app: alpine-sleep
    spec:
      containers:
        - name: alpine
          image: alpine
          command: ["sh", "-c", "sleep infinity"]
